services:
  - type: web
    name: shree-vidya-api
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5000
      - key: CLIENT_URL
        value: https://shreevidyaclothing.vercel.app
      - key: SUPABASE_URL
        value: https://xzrcywybufifjxhjxcqt.supabase.co
      - key: ADMIN_ID
        value: your-admin-id
      - key: ADMIN_PASSWORD
        value: set-in-render-dashboard
